[package]
name = "distributed_systems_rust_stuff"
version = "0.1.0"
authors = ["Rahim Klab√©r <rahimklaber2@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
